blank_issues_enabled: true
contact_links:
  - name: Element iOS Community Support
    url: "https://matrix.to/#/#element-ios:matrix.org"
    about: General Element iOS support questions can be asked here.
  - name: Matrix Security Policy
    url: https://www.matrix.org/security-disclosure-policy/
    about: Learn more about our security disclosure policy.
